
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T) 
```

##Libraries
```{r, echo=F}
library( geojsonio )   # read shapefiles
library( sp )          # work with shapefiles
library( sf )          # work with shapefiles - simple features format
library( mclust )      # cluster analysis 
library( tmap )        # theme maps
library( ggplot2 )     # graphing 
library( ggthemes )    # nice formats for ggplots
library( dplyr )       # data wrangling 
library( pander )      # formatting RMD tables
library( tidycensus )

library( cartogram )  # spatial maps w/ tract size bias reduction
library( maptools )   # spatial object manipulation 
library( corrplot )

census_api_key("bd4e0abad62119c3a101ec5cdfacfb5c4070a6bf")
install = TRUE
```


## Obtain and Load Data
```{r}
options(tigris_use_cache = TRUE)
cw <- read.csv( "https://raw.githubusercontent.com/DS4PS/cpp-529-master/master/data/cbsatocountycrosswalk.csv",  stringsAsFactors=F, colClasses="character" )

# search for cities names San Diego 
# grep( "^SAN DIEGO, CA", cw$msaname, value=TRUE ) 

these.msa <- cw$msaname == "SAN DIEGO, CA"

# Get the FIPS codes for the selected MSA
these.fips <- cw$fipscounty[these.msa]
these.fips <- na.omit(these.fips)

# Get San Diego
sdd.pop <- get_acs( 
  geography = "tract", 
  variables = "B01003_001", 
  state = "06", 
  county = "073",
  geometry = TRUE ) %>% 
  select( GEOID, estimate ) %>%
  rename( POP=estimate )

# Load Census data
URL <- "https://github.com/DS4PS/cpp-529-master/raw/master/data/ltdb_std_2010_sample.rds"
census.data <- readRDS(gzcon(url(URL)))

# remove leading 0s
sdd.pop$GEOID<-sub( ".","", sdd.pop$GEOID )

# merge the pop data for san diego with the census data
sdd <- merge( sdd.pop, census.data, by.x="GEOID", by.y="tractid" )

# make sure there are no empty polygons
sdd_merged <- sdd[ ! st_is_empty( sdd ), ]
```


## San Diego Shapefile
```{r}
# dorling cartogram of San Diego Census Tracts
# Convert the sf map object to an sp version
sdd.sp <- as_Spatial(sdd_merged)

# Project map and remove empty tracts
sdd.sp <- spTransform( sdd.sp, CRS("+init=epsg:3395"))
sdd.sp <- sdd.sp[ sdd.sp$POP != 0 & (! is.na( sdd.sp$POP )), ]

# Convert census tract polygons to a Dorling cartogram
sdd.sp$pop.w <- sdd.sp$POP / 9000 # max(sdd.sp$POP)   # scaling to max of 1.5
sdd_dorling <- cartogram_dorling( x=sdd.sp, weight="pop.w", k=0.05 )

# Plot the Dorling cartogram
plot(sdd_dorling)
```


```{r}
# Project map of sdd_dorling
sdd_dorling <- spTransform(sdd_dorling, CRS("+init=epsg:3395"))

# Define bounding outline for the San Diego area
bb <- st_bbox(c(xmin = -13100000, xmax = -12850000,
                ymax = 4025000, ymin = 3775000),
              crs = st_crs("+init=epsg:3395"))

# tmap visualization for the Dorling cartogram
tm_shape(sdd_dorling, bbox = bb) +
  tm_polygons(col = "hinc12", n = 10, style = "quantile", palette = "Spectral") +
  tm_layout("San Diego Dorling Cartogram", title.position = c("right", "top"))
```

```{r}
tmap_mode("view")
tm_basemap( "HikeBike.HillShading"  ) +
  tm_shape( sdd_dorling, bbox=bb ) + 
  tm_polygons( col="phisp12", n=7, style="quantile", palette="-inferno" ) 
```

```{r}
tm_basemap( "Stamen.Watercolor" ) +
tm_shape( sdd_dorling, bbox=bb ) + 
  tm_polygons( col="hinc12", n=7, style="quantile", palette="RdYlBu" ) +
  tm_legend( show=FALSE )
```


## Census Variables
##Extract data from the shapefile. Save as a separate data frame 
```{r}
d1 <- sdd_dorling@data
```


## Prepare Data for Clustering
```{r}
keep.these <- c("pnhwht12", "pnhblk12", "phisp12", "pntv12", "pfb12", "polang12", 
"phs12", "pcol12", "punemp12", "pflabf12", "pprof12", "pmanuf12", 
"pvet12", "psemp12", "hinc12", "incpc12", "ppov12", "pown12", 
"pvac12", "pmulti12", "mrent12", "mhmval12", "p30old12", "p10yrs12", 
"p18und12", "p60up12", "p75up12", "pmar12", "pwds12", "pfhh12")

d2 <- select( d1, keep.these )
d3 <- apply( d2, 2, scale )
```


## Prepare Cluster Analysis
```{r}
set.seed( 1234 )
fit <- Mclust( d3 )
sdd_dorling$cluster <- as.factor( fit$classification )
summary( fit )
```


```{r, echo=TRUE,warning=FALSE}

URL1 <- "https://github.com/DS4PS/cpp-529-fall-2020/raw/main/LABS/data/rodeo/LTDB-2000.rds"
df1 <- readRDS( gzcon( url( URL1 ) ) )

URL2 <- "https://github.com/DS4PS/cpp-529-fall-2020/raw/main/LABS/data/rodeo/LTDB-2010.rds"
df2 <- readRDS( gzcon( url( URL2 ) ) )

URLmd <- "https://github.com/DS4PS/cpp-529-fall-2020/raw/main/LABS/data/rodeo/LTDB-META-DATA.rds"
md <- readRDS( gzcon( url( URLmd ) ) )

df1 <- select( df1, - year )
df2 <- select( df2, - year )

d0 <- merge( df1, df2, by="tractid" )
d0 <- merge( d0, md, by="tractid" )

# Filter out rural
d0 <- filter( d0, urban == "urban" )
# Create new variables
d0 <- select( d0, tractid, 
             mhmval00, mhmval12, 
             hinc00, 
             hu00, vac00, own00, rent00, h30old00,
             empclf00, clf00, unemp00, prof00,  
             dpov00, npov00,
             ag25up00, hs00, col00, 
             pop00.x, nhwht00, nhblk00, hisp00, asian00,
             cbsa, cbsaname )

d0 <- 
  d0 %>%
  mutate( # percent white in 2000
          p.white = 100 * nhwht00 / pop00.x,
          # percent black in 2000
          p.black = 100 * nhblk00 / pop00.x,
          # percent hispanic in 2000
          p.hisp = 100 * hisp00 / pop00.x, 
          # percent asian in 2000
          p.asian = 100 * asian00 / pop00.x,
          # percent high school grads by age 25 in 2000 
          p.hs = 100 * (hs00+col00) / ag25up00,
          # percent pop with college degree in 2000
          p.col = 100 * col00 / ag25up00,
          # percent employed in professional fields in 2000
          p.prof = 100 * prof00 / empclf00,
          # percent unemployment  in 2000
          p.unemp = 100 * unemp00 / clf00,
          # percent of housing lots in tract that are vacant in 2000
          p.vacant = 100 * vac00 / hu00,
          # dollar change in median home value 2000 to 2010 
          pov.rate = 100 * npov00 / dpov00 )


# adjust 2000 home values for inflation 
mhv.00 <- d0$mhmval00 * 1.28855  
mhv.10 <- d0$mhmval12

# change in MHV in dollars
mhv.change <- mhv.10 - mhv.00

# drop low 2000 median home values to avoid unrealistic growth rates.

# tracts with homes that cost less than $1,000 are outliers
mhv.00[ mhv.00 < 1000 ] <- NA

# change in MHV in percent
mhv.growth <- 100 * ( mhv.change / mhv.00 )

d0$mhv.00 <- mhv.00
d0$mhv.10 <- mhv.10
d0$mhv.change <- mhv.change
d0$mhv.growth <- mhv.growth 

x <- d0$tractid 
x <- gsub( "fips", "", x )
x <- gsub( "-", "", x )

# drop leading zeros 
x <- as.numeric( x )

# remember to add the variable back to the census dataset
d0$tractid2 <- x 

d0$tractid2 <- as.character(d0$tractid2)
sddDorling <- merge(sdd_dorling, d0, by.x="GEOID", by.y="tractid2", all.x=T )
```

```{r }

row.ids <- sapply(slot(sddDorling, "polygons"), function(x) slot(x, "ID"))
row.names(sddDorling) <- row.ids

sddDorling <- spTransform(sddDorling, CRS("+proj=longlat +datum=WGS84"))

geojson_write(sddDorling, file="sd_dorling.geojson", geometry="polygon")
```
